version: 1

formatters:
  simple:
    format: '%(asctime)s %(name)s [%(levelname)s] %(message)s'
  method:
    format: '%(asctime)s %(name)s:%(funcName)s [%(levelname)s] %(message)s'
  trace:
    format: '%(asctime)s %(name)s@%(filename)s:%(lineno)d:%(funcName)s [%(levelname)s] %(message)s'
  input:
    format: '%(message)s'
  output:
    format: '#%(message)s'

filters:
  UltraVoltageFilter:
    class: ext://TimingDevices.UltraVoltageFilter
#    '()': ext://TimingDevices.UltraTimingDevice.UltraVoltageFilter

objects:
  decoder_log_queue:
    class: queue.Queue
    maxsize: 1000

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
    filters:
      - UltraVoltageFilter
#  file:
#    class: logging.FileHandler
#    delay: true
#    formatter: method
#    filename: logs/crossmgr.log
#    encoding: utf-8
  file:
    '()': ext://Log.owned_file_handler
    formatter: method
    filename: 'logs/crossmgr.log'
    encoding: utf-8
  decoder_input_file:
    # TODO: Replace this with a single handler for I/O.
#    class: logging.FileHandler
#    delay: true
    '()': ext://Log.owned_file_handler
    formatter: input
    filename: logs/decoder.log
    encoding: utf-8
  decoder_output_file:
    # TODO: Replace this with a single handler for I/O.
#    class: logging.FileHandler
#    delay: true
    '()': ext://Log.owned_file_handler
    formatter: output
    filename: logs/decoder-out.log
    encoding: utf-8
#  decoder_log_queue:
##    class: logging.handlers.QueueListener
##    class: ext://QueueListenerHandler
#    class: TimingDevices.QueueListenerHandler
##    '()': ext://LogRedirect.QueueListenerHandler
##    class: LogRedirect.QueueListenerHandler
#    queue: cfg://objects.decoder_log_queue
#    handlers:
#    - console
#    - file

loggers:
#  'TimingDevice[UltraDecoder]':
#    level: INFO
#    handlers:
#    - decoder_log_queue
#    propagate: false
  'TimingDevice[UltraDecoder].input':
    level: INFO
    handlers:
    - decoder_input_file
#    - decoder_log_queue
#    propagate: false
  'TimingDevice[UltraDecoder].output':
    level: INFO
    handlers:
    - decoder_output_file
#    - decoder_log_queue
#    propagate: false
  root:
    class: CrossMgrLogger
    level: INFO
    handlers:
    - console
    - file
